<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.5" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_height" value="0.5" />

    <link name="world"></link>

    <link name="box_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <joint name="world_box_joint" type="planar">
        <parent link="world" />
        <child link="box_link" />
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

</robot>
